import { K2D } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nav/Navbar";

const k2d = K2D({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";
import ClientLayout from "@/components/ClientLayout";
import { Toaster } from "@/components/ui/toaster";

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={k2d.className}>
        <Toaster />
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
